name: NAIS Deploy

on:
  workflow_call:
    inputs:
      cluster:
        required: false
        type: string
      resource:
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Environment
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.cluster || 'dev-gcp' }}
          RESOURCE: ${{ inputs.resource || '.nais/naiserator-dev.yaml' }}
          IMAGE: ${{ needs.build.outputs.image }}
          TIMEOUT: 10m
          PRINT_PAYLOAD: true
